import { readFile } from 'fs/promises'
import path from 'path'
import { NextResponse } from 'next/server'

import { isStaffUser } from '@/access'
import { getAgreement, saveAgreement } from '@/lib/agreementStore'
import { botPayload } from '@/lib/botServer'
import { agreementFileName, agreementValues, fillAgreement } from '@/lib/leaseAgreement'
import { notifyFromBooking } from '@/lib/notify'
import { passportStatus } from '@/lib/passport'
import { findStudentByWhatsapp } from '@/lib/studentAuth'

export const dynamic = 'force-dynamic'

const DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'

async function staffAndBooking(request: Request, params: Promise<{ id: string }>) {
  const payload = await botPayload()
  const { user } = await payload.auth({ headers: request.headers })
  if (!isStaffUser(user)) return { error: NextResponse.json({ ok: false, error: 'Staff login required' }, { status: 401 }) }
  const { id } = await params
  const booking: any = await payload.findByID({ collection: 'v1-bot-bookings', id, overrideAccess: true, depth: 0 }).catch(() => null)
  if (!booking || booking.type !== 'bed_hold') return { error: NextResponse.json({ ok: false, error: 'Booking not found' }, { status: 404 }) }
  return { payload, user: user as any, booking }
}

/**
 * GET /api/staff/bookings/:id/agreement (staff login required)
 * The booking's agreement as it was generated, as a Word file (`?download=1` to save it).
 */
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const found = await staffAndBooking(request, params)
  if ('error' in found) return found.error
  const stored = await getAgreement(found.payload, String(found.booking.id))
  if (!stored) return NextResponse.json({ ok: false, error: 'No agreement has been generated for this booking yet.' }, { status: 404 })
  const download = new URL(request.url).searchParams.get('download') === '1'
  return new Response(Buffer.from(stored.data), {
    headers: {
      'Content-Type': DOCX,
      'Content-Disposition': `${download ? 'attachment' : 'inline'}; filename="${agreementFileName(found.booking)}"`,
      'Cache-Control': 'private, no-store',
    },
  })
}

/**
 * POST /api/staff/bookings/:id/agreement (staff login required)
 * Generates the lease agreement once: fills the template from the booking, its property, the
 * unit and the student's verified passport, and keeps that file. Only for paid bookings with a
 * verified passport; a booking that already has an agreement is refused (409, `exists`).
 */
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const found = await staffAndBooking(request, params)
  if ('error' in found) return found.error
  const { payload, user, booking } = found

  if (await getAgreement(payload, String(booking.id))) {
    return NextResponse.json({ ok: false, reason: 'exists', error: 'The agreement for this booking has already been generated.' }, { status: 409 })
  }
  if (booking.status !== 'paid') {
    return NextResponse.json({ ok: false, error: 'The agreement is generated once the booking is paid.' }, { status: 409 })
  }

  const [property, student, unit] = await Promise.all([
    booking.propertyId
      ? payload.findByID({ collection: 'v1-properties', id: booking.propertyId, overrideAccess: true, depth: 0 }).catch(() => null)
      : null,
    booking.whatsapp ? findStudentByWhatsapp(payload, booking.whatsapp) : null,
    // The unit's current rent, for bookings made before it had one
    booking.overrideKey
      ? payload
          .find({ collection: 'v1-room-overrides', where: { overrideKey: { equals: booking.overrideKey } }, limit: 1, depth: 0, overrideAccess: true })
          .then((r) => (r.docs[0] as any) || null)
      : null,
  ])
  if (passportStatus(student) !== 'verified') {
    return NextResponse.json({ ok: false, error: "The student's passport must be verified first." }, { status: 409 })
  }

  const template = await readFile(path.join(process.cwd(), 'src/templates/lease-agreement.docx'))
  const file = fillAgreement(new Uint8Array(template), agreementValues(booking, property, student, unit))
  const by = String(user?.username || user?.email || 'staff')
  if (!(await saveAgreement(payload, booking, file, by))) {
    return NextResponse.json({ ok: false, reason: 'exists', error: 'The agreement for this booking has already been generated.' }, { status: 409 })
  }
  const generatedAt = new Date().toISOString()
  await payload.update({
    collection: 'v1-bot-bookings',
    id: booking.id,
    overrideAccess: true,
    data: {
      agreementGeneratedAt: generatedAt,
      notes: [booking.notes, `Agreement generated by ${by} ${generatedAt}.`].filter(Boolean).join('\n'),
    } as any,
  })
  // Tell the student on WhatsApp (sent once: an agreement is generated once per booking)
  await notifyFromBooking('contract_generated', booking, payload, { origin: new URL(request.url).origin })
  return NextResponse.json({ ok: true, generatedAt, generatedBy: by })
}
